title: GOBLET
description: Global Organisation for Bioinformatics Learning, Education & Training
show_downloads: true
theme: jekyll-theme-cayman
url: mygobletorg.github.io

# Social Media

twitter_username: mygobletorg
github_username:  mygobletorg

# Build settings
markdown: kramdown

# Google Services

google_analytics:
